import sys
import os
import glob

def load_map(filepath):
    """
    Reads a .per_query file generated by 'trec_eval -q -m map'.
    Returns a dictionary: {qid: map_score}
    """
    scores = {}
    try:
        with open(filepath, 'r') as f:
            for line in f:
                parts = line.split()
                # Format expected: map qid value
                # Ignore the 'all' summary line if present
                if len(parts) == 3 and parts[0] == 'map' and parts[1] != 'all':
                    scores[parts[1]] = float(parts[2])
    except Exception as e:
        # Silently fail or print error if needed, returning empty dict
        return {}
    return scores

def main():
    # Ensure Output Directory argument is provided
    if len(sys.argv) < 2:
        print("Usage: python calc_wtl.py <OUTPUT_DIR>")
        sys.exit(1)

    out_dir = sys.argv[1]
    
    # 1. Identify the Baseline File
    # Experiment 1 baseline is always HW2-Exp-1.1a (BM25)
    baseline_id = "HW2-Exp-1.1a"
    baseline_file = os.path.join(out_dir, f"{baseline_id}.per_query")
    
    # Load baseline scores
    base_scores = load_map(baseline_file)
    if not base_scores:
        print(f"Error: Baseline file '{baseline_file}' not found or empty.")
        return

    # 2. Find all Experiment files
    # Looks for any file matching the pattern HW2-Exp-1.*.per_query
    files = sorted(glob.glob(os.path.join(out_dir, "HW2-Exp-1.*.per_query")))
    
    print("\n=== Win / Tie / Loss Stats (Baseline: 1.1a) ===")
    print(f"{'Experiment':<20} | {'Win / Tie / Loss'}")
    print("-" * 45)

    for f in files:
        # Extract experiment name from filename
        exp_name = os.path.basename(f).replace(".per_query", "")
        
        # Skip comparing baseline to itself
        if exp_name == baseline_id:
            print(f"{exp_name:<20} | n/a")
            continue

        # Load experiment scores
        exp_scores = load_map(f)
        
        wins = 0
        ties = 0
        losses = 0
        
        # Compare scores for each query
        for qid in base_scores:
            if qid not in exp_scores: 
                continue
            
            b_map = base_scores[qid]
            e_map = exp_scores[qid]
            
            # Calculate Win/Tie/Loss
            # Threshold is +/- 2.0% (0.02)
            
            if b_map == 0:
                # If baseline is 0, any positive score is a win
                if e_map > 0: 
                    wins += 1
                else: 
                    ties += 1
            else:
                diff = (e_map - b_map) / b_map
                
                if diff >= 0.02: 
                    wins += 1
                elif diff <= -0.02: 
                    losses += 1
                else: 
                    ties += 1
        
        # Print formatted result
        print(f"{exp_name:<20} | {wins:02d} / {ties:02d} / {losses:02d}")
        
    print("==============================================\n")

if __name__ == "__main__":
    main()