import sys
import os
import glob

def load_map(filepath):
    """Reads a .per_query file generated by 'trec_eval -q -m map'."""
    scores = {}
    try:
        with open(filepath, 'r') as f:
            for line in f:
                parts = line.split()
                if len(parts) == 3 and parts[0] == 'map' and parts[1] != 'all':
                    scores[parts[1]] = float(parts[2])
    except:
        return {}
    return scores

def calculate_wtl(base_scores, exp_scores):
    """Calculates Win/Tie/Loss with 2% threshold."""
    if not base_scores or not exp_scores: return "n/a"
    
    wins, ties, losses = 0, 0, 0
    for qid in base_scores:
        if qid not in exp_scores: continue
        b = base_scores[qid]
        e = exp_scores[qid]
        
        if b == 0:
            if e > 0: wins += 1
            else: ties += 1
        else:
            diff = (e - b) / b
            if diff >= 0.02: wins += 1
            elif diff <= -0.02: losses += 1
            else: ties += 1
    return f"{wins:02d} / {ties:02d} / {losses:02d}"

def main():
    if len(sys.argv) < 2:
        print("Usage: python calc_wtl_exp3.py <OUTPUT_DIR>")
        sys.exit(1)

    out_dir = sys.argv[1]
    
    # Baseline for Exp 3 is Exp-1.2b (RM3, Body, Weight 0.0)
    baseline_file = os.path.join(out_dir, "HW2-Exp-1.2b.per_query")
    base_scores = load_map(baseline_file)
    
    if not base_scores:
        print(f"Error: Baseline file (1.2b) not found in {out_dir}")
        return

    # Find Exp 3 files (3.1b to 3.1f)
    files = sorted(glob.glob(os.path.join(out_dir, "HW2-Exp-3.1*.per_query")))
    
    print("\n=== Win / Tie / Loss (Baseline: Exp-1.2b) ===")
    print(f"{'Experiment':<20} | {'W / T / L'}")
    print("-" * 40)

    for f in files:
        exp_name = os.path.basename(f).replace(".per_query", "")
        result = calculate_wtl(base_scores, load_map(f))
        print(f"{exp_name:<20} | {result}")
    print("=============================================\n")

if __name__ == "__main__":
    main()