import sys
import os
import glob

def load_map(filepath):
    """
    Reads a .per_query file generated by 'trec_eval -q -m map'.
    Returns a dictionary: {qid: map_score}
    """
    scores = {}
    try:
        with open(filepath, 'r') as f:
            for line in f:
                parts = line.split()
                # Format expected: map qid value
                # Ignore the 'all' summary line if present
                if len(parts) == 3 and parts[0] == 'map' and parts[1] != 'all':
                    scores[parts[1]] = float(parts[2])
    except Exception as e:
        # Silently fail or print error if needed, returning empty dict
        print(f"Error reading {filepath}: {e}")
        return {}
    return scores

def calculate_wtl_string(base_scores, exp_scores):
    """
    Calculates Win/Tie/Loss statistics and returns a formatted string.
    Threshold: +/- 2.0% (0.02)
    """
    if not base_scores or not exp_scores:
        return "n/a"
        
    wins, ties, losses = 0, 0, 0
    
    for qid in base_scores:
        if qid not in exp_scores: continue
        
        b = base_scores[qid]
        e = exp_scores[qid]
        
        if b == 0:
            # If baseline is 0, any positive score is a win
            if e > 0: wins += 1
            else: ties += 1
        else:
            diff = (e - b) / b
            
            if diff >= 0.02: 
                wins += 1
            elif diff <= -0.02: 
                losses += 1
            else: 
                ties += 1
            
    # Return formatted string: 00 / 00 / 00
    return f"{wins:02d} / {ties:02d} / {losses:02d}"

def main():
    if len(sys.argv) < 2:
        print("Usage: python calc_wtl_exp2.py <OUTPUT_DIR>")
        sys.exit(1)

    out_dir = sys.argv[1]
    
    # Define filenames for the two specific baselines
    # Note: These files must be copied from HW2-EXP1 by the shell script
    base_okapi_file = os.path.join(out_dir, "HW2-Exp-1.1b.per_query")
    base_rm3_file   = os.path.join(out_dir, "HW2-Exp-1.2b.per_query")
    
    # Load Baseline Data
    scores_base_okapi = load_map(base_okapi_file)
    scores_base_rm3   = load_map(base_rm3_file)
    
    if not scores_base_okapi:
        print(f"Warning: Okapi Baseline (1.1b) not found in {out_dir}")
    if not scores_base_rm3:
        print(f"Warning: RM3 Baseline (1.2b) not found in {out_dir}")

    # Find all per_query files for Experiment 2
    files = sorted(glob.glob(os.path.join(out_dir, "HW2-Exp-2.*.per_query")))
    
    print("\n=== Win / Tie / Loss Stats for Exp 2 ===")
    print(f"{'Experiment':<20} | {'Baseline':<15} | {'W / T / L'}")
    print("-" * 55)

    for f in files:
        exp_name = os.path.basename(f).replace(".per_query", "")
        
        # Determine if this experiment belongs to Okapi Group (2.1x) or RM3 Group (2.2x)
        if "Exp-2.1" in exp_name:
            # Compare against Okapi Baseline (1.1b)
            baseline_name = "Exp-1.1b"
            result = calculate_wtl_string(scores_base_okapi, load_map(f))
        elif "Exp-2.2" in exp_name:
            # Compare against RM3 Baseline (1.2b)
            baseline_name = "Exp-1.2b"
            result = calculate_wtl_string(scores_base_rm3, load_map(f))
        else:
            baseline_name = "Unknown"
            result = "n/a"
            
        print(f"{exp_name:<20} | {baseline_name:<15} | {result}")
        
    print("========================================\n")

if __name__ == "__main__":
    main()